### numpy基础数据类型

In [4]:
import numpy as np 
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [5]:
b = np.arange(12).reshape(3,4)
print(type(b),",",b.dtype)
print(b.ndim)
a = np.array(['a','b'])
b = b.astype(a.dtype)
b

<class 'numpy.ndarray'> , int64
2


array([['0', '1', '2', '3'],
       ['4', '5', '6', '7'],
       ['8', '9', '1', '1']],
      dtype='<U1')

astype 将数组中的所有元素都转换类型


In [6]:
n = np.random.randn(3,4)
n

array([[-0.69742211,  0.10107982, -1.60940491,  1.11566479],
       [-0.93757754, -0.23891789, -1.22564441, -0.56396475],
       [ 1.07680702, -1.4933232 ,  0.6735455 ,  0.61599798]])

In [7]:
n.transpose(), n.T

(array([[-0.69742211, -0.93757754,  1.07680702],
        [ 0.10107982, -0.23891789, -1.4933232 ],
        [-1.60940491, -1.22564441,  0.6735455 ],
        [ 1.11566479, -0.56396475,  0.61599798]]),
 array([[-0.69742211, -0.93757754,  1.07680702],
        [ 0.10107982, -0.23891789, -1.4933232 ],
        [-1.60940491, -1.22564441,  0.6735455 ],
        [ 1.11566479, -0.56396475,  0.61599798]]))

In [8]:
b = np.array([1,2,3])
np.tile(b,(2,3))

array([[1, 2, 3, 1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3, 1, 2, 3]])

In [9]:
a = np.array([1,2,3])
np.mat(a)

matrix([[1, 2, 3]])

In [10]:
a = np.zeros((2,3,4,5))
a

array([[[[ 0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.]],

        [[ 0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.]],

        [[ 0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.]]],


       [[[ 0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.]],

        [[ 0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.]],

        [[ 0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.]]]])

- 四维数组（2*3*4*5）由2个三维数组（3*4*5）组成
- 每个三维数组由三个两维数组构成。
- 每个两维数组由4个一维数组构成
- 每个一维数组由5个数构成

In [11]:
np.random.normal(100,size=(4,4)) #正太分布

array([[ 100.43022692,   99.5550081 ,   99.94823209,  101.02989944],
       [  98.94188471,   99.55144559,  101.087488  ,  101.93480912],
       [ 100.75153805,  100.21468227,  101.61317575,  100.69573345],
       [  98.83582067,  101.0982656 ,  100.70204078,   99.72237468]])

In [12]:
a = np.array([2,3,4,3,3,2,1])
np.unique(a)

array([1, 2, 3, 4])

相当于set并排序

###  运算

In [13]:
arr = np.array([[1,2,3],[4,5,6]])
arr.sum()

21

In [14]:
arr*arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [15]:
np.sqrt(arr)

array([[ 1.        ,  1.41421356,  1.73205081],
       [ 2.        ,  2.23606798,  2.44948974]])

- array 数组使你不用进行循环就能进行批量运算。
- 对 array数组直接使用运算符，相当于所有元素对应进行运算。

In [16]:
arr_1 = np.array([[1,2],[3,4]])
arr_2 = np.array([[2,3],[4,5]])
np.dot(arr_1,arr_2)

array([[10, 13],
       [22, 29]])

### 切片

In [17]:
arr = np.arange(10)
arr[5:8] = 666
arr

array([  0,   1,   2,   3,   4, 666, 666, 666,   8,   9])

将一个标量赋值给一个数组切片时，该值会自动广播到整个选区。


In [18]:
arr_slice = arr[5:8]
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

array类型被切片后不会赋值，只保留一份数据。

In [19]:
arr_2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2[0][2],arr_2[0,2])
print(arr_2[:2,1:])


3 3
[[2 3]
 [5 6]]


In [21]:
arr = np.random.rand(3,4)
print(arr)
print(arr[[True,False,True]])

[[ 0.96786834  0.36357933  0.22567917  0.52341847]
 [ 0.68798364  0.37397368  0.27018109  0.79848626]
 [ 0.41673112  0.48258395  0.78944675  0.5498687 ]]
[[ 0.96786834  0.36357933  0.22567917  0.52341847]
 [ 0.41673112  0.48258395  0.78944675  0.5498687 ]]


用布尔型列表切片数组

In [ ]:
arr[arr<0.5] =  0
arr

按条件批量改变数组的值

In [ ]:
arr = np.random.rand(4,4)
print(arr)
np.where(arr>0.5,'>0.5','<0.5')

In [ ]:
np.where(arr>0.5, '>0.5' ,arr)

In [ ]:
arr_file = np.loadtxt('Iris.txt',dtype= str)
arr_file


# matplotlib 

In [ ]:
import matplotlib.pyplot as plt
import numpy as np 

x = [1,2,3]
y = [2,4,6] 
plt.plot(x,y)
plt.show() 

In [ ]:
import matplotlib.pyplot as plt
import numpy as np 

x = np.array([1,2,3]) 
y = x 
y0 = 0*x
y1 = 0.5*x 
y2 = 2*x 

def loss(y,y1):
    s = 0 
    for i in range(len(y)):
        s += (y1[i] - y[i])**2    
    return s/(2*len(y))
        
l0 = loss(y,y0)
l1 = loss(y,y1)
l2 = loss(y,y2)

plt.plot(x,y,label = 'y = x')
plt.plot(x,y0,label = 'y = 0')
plt.plot(x,y1,label = 'y = 0.5*x')
plt.plot(x,y2,label = 'y=2*x')

theta = [0,0.5,2]
plt.plot(theta,[l0,l1,l2])


plt.show() 


In [ ]:
from scipy.misc import imread,imsave,imresize 
img = imread('dog.jpg')
print(img.shape)
# img_re = imresize(img,(300,300))
# imsave('dog_re',img_re)
