In [109]:
import torch 
import torchvision
import torch.nn as nn
import numpy as np
import torchvision.transforms as transforms

In [110]:
x = torch.tensor(1.0 ,requires_grad = True)
w = torch.tensor(2.0 ,requires_grad = True)
b = torch.tensor(3.0 ,requires_grad = True)

In [111]:
y = w * x  + b 

In [112]:
y.backward()
x.grad , w.grad , b.grad 

(tensor(2.), tensor(1.), tensor(1.))

In [113]:
x = torch.randn(10,3)
y = torch.randn(10,2)

In [114]:
linear = nn.Linear(3,2)
linear.weight  , linear.bias

(Parameter containing:
 tensor([[ 0.2912,  0.0606, -0.2572],
         [ 0.3880, -0.3268, -0.3197]], requires_grad=True),
 Parameter containing:
 tensor([-0.3683, -0.3784], requires_grad=True))

In [115]:
criterion = nn.MSELoss()
optimizer = torch.optim.SGD(linear.parameters(), lr=0.01)

In [116]:
pred = linear(x)

In [117]:
loss = criterion(pred,y)
loss.item()

1.201653003692627

In [118]:
loss.backward()

In [119]:
linear.weight.grad  , linear.bias.grad 

(tensor([[-0.1742, -0.3191, -0.0954],
         [ 0.5512, -1.0378, -0.0775]]), tensor([-0.6213,  0.2423]))

In [120]:
optimizer.step()
pred = linear(x)
loss = criterion(pred,y )
loss.item()

1.1820515394210815

In [121]:
x = np.array([[1,2],[3,4]])

In [122]:
y = torch.from_numpy(x)
y

tensor([[1, 2],
        [3, 4]])

In [123]:
z = y.numpy()
z

array([[1, 2],
       [3, 4]])

### input pipline 

In [125]:
train_dataset = torchvision.datasets.CIFAR10(root='../../data/',
                                             train=True, 
                                             transform=transforms.ToTensor(),
                                             download=True)


Files already downloaded and verified


In [126]:
image , label = train_dataset[0]

In [131]:
image.size(), label

(torch.Size([3, 32, 32]), 6)

In [132]:
train_loader = torch.utils.data.DataLoader(dataset=train_dataset, batch_size = 64 , shuffle = True )


In [133]:
data_iter = iter(train_loader)

In [134]:
images , labels = data_iter.next()

In [135]:
for images , labels in train_loader:
    pass 
