In [1]:
import torch

In [3]:
x = torch.Tensor(2,4) # 2*4 dim matrix

In [4]:
x

tensor([[2.4517e-26, 4.5751e-41, 2.6315e-29, 4.5751e-41],
        [2.6113e-29, 4.5751e-41, 2.6396e-29, 4.5751e-41]])

In [8]:
type(x), x.type(), x.dtype

(torch.Tensor, 'torch.FloatTensor', torch.float32)

In [15]:
l = [[1,2,3],[4,5,6],[7,8,9]]
x = torch.tensor(l)
x

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [18]:
x[0][2] = 99

In [19]:
x

tensor([[ 1,  2, 99],
        [ 4,  5,  6],
        [ 7,  8,  9]])

### create tensor
- torch.zeros()
- torch.ones()
- torch.eye()
- torch.rand() 生成 0-1的随机数
- torch.randn() 服从标准正态分布的随机数
- torch.arange()
- torch.from_numpy()

In [22]:
torch.arange(1,10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

### cat chunk view
cat 
chunk

### math function
- add
- mul
- div
- fmod
- abs
- ceil
- floor 
- clamp
- round
- frac
- neg
- reciprocal 倒数
- log
- pow
- exp
- sigmod
- sign
- sqrt
- dist
- mean
- norm
- prod
- sum
- max
- min 

In [29]:
x.norm()

RuntimeError: norm only supports floating-point dtypes

In [44]:
x = torch.rand((2,3))
x

tensor([[0.7657, 0.0209, 0.4987],
        [0.8196, 0.1245, 0.5326]])

In [47]:
x.reciprocal()

tensor([[ 1.3059, 47.8144,  2.0054],
        [ 1.2201,  8.0290,  1.8775]])

In [34]:
x.norm()

tensor(0.9414)

In [36]:
x.dist()

TypeError: dist() missing 1 required positional arguments: "other"

In [43]:
x.clamp(2)

tensor([[2., 2., 2.],
        [2., 2., 2.]])

### 线性代数运算
- dot 
- mm
- mv 
- bmm
- inverse
- eig
- ger