In [3]:
import torch 
import torchvision
import torch.nn as nn
import numpy as np
import torchvision.transforms as transforms

###  example 1
$y = wX + b$

In [3]:
x = torch.tensor(1.0 ,requires_grad = True)
w = torch.tensor(2.0 ,requires_grad = True)
b = torch.tensor(3.0 ,requires_grad = True)

In [4]:
x

tensor(1., requires_grad=True)

In [5]:
y = w * x  + b 

In [6]:
y.backward()
x.grad , w.grad , b.grad 

(tensor(2.), tensor(1.), tensor(1.))

### example 2 

In [7]:
x = torch.randn(10,3) #定义输入
y = torch.randn(10,2) #label

In [12]:
x

tensor([[-1.0658,  0.3547, -0.3832],
        [ 0.2252,  0.7450,  1.4454],
        [-0.5392,  0.0554,  0.9105],
        [-2.0828, -0.7130,  0.5574],
        [-0.1443,  0.8941,  1.3014],
        [ 0.0508,  0.6613,  1.7755],
        [-0.3732, -1.2301, -0.0976],
        [ 0.4231,  0.3660, -0.2223],
        [ 0.9752, -3.1922,  2.2652],
        [ 0.2382, -0.4254, -0.4076]])

In [17]:
x.transpose(0,1)

tensor([[-1.0658,  0.2252, -0.5392, -2.0828, -0.1443,  0.0508, -0.3732,  0.4231,
          0.9752,  0.2382],
        [ 0.3547,  0.7450,  0.0554, -0.7130,  0.8941,  0.6613, -1.2301,  0.3660,
         -3.1922, -0.4254],
        [-0.3832,  1.4454,  0.9105,  0.5574,  1.3014,  1.7755, -0.0976, -0.2223,
          2.2652, -0.4076]])

In [63]:
linear = nn.Linear(3,2) #创建一个全联接的网络 ，有初始化的w 和 b 
linear.weight  , linear.bias 

(Parameter containing:
 tensor([[ 0.1970, -0.3254,  0.3841],
         [ 0.5234, -0.5638, -0.5132]], requires_grad=True),
 Parameter containing:
 tensor([-0.2507,  0.3908], requires_grad=True))

In [47]:
criterion = nn.MSELoss()   #定义损失函数
optimizer = torch.optim.SGD(linear.parameters(), lr=0.01) # 随机梯度下降

In [48]:
pred = linear(x) # 预测值 等于输入值经过网络 

In [49]:
loss = criterion(pred,y)   # 预测值与真实值计算误差
np.sqrt(loss.item()) 

0.80408243930732815

In [50]:
type(loss)

torch.Tensor

In [51]:
loss.backward() #反向传播 

In [52]:
linear.weight.grad  , linear.bias.grad  # 计算梯度 

(tensor([[-0.0632, -0.6091, -0.2261],
         [ 0.2343,  0.1718, -0.0515]]), tensor([0.0477, 0.2120]))

In [53]:
optimizer.step() # 一次随机梯度下降  ，权值更新

In [54]:
linear.weight  

Parameter containing:
tensor([[-0.1362, -0.0805,  0.2744],
        [ 0.5351,  0.1266, -0.1395]], requires_grad=True)

In [59]:
pred = linear(x) # 重新预测
loss = criterion(pred,y) # 重新计算误差
np.sqrt(loss.item()) #误差降低 

0.80062243119482102

### example 3

$$
\left[
\begin{matrix}
1 & 2 \\
3 & 3 \\
\end{matrix}
\right]
$$

In [2]:
x = np.array([[1,2],[3,4]])

NameError: name 'np' is not defined

In [38]:
y = torch.from_numpy(x)
y

tensor([[1, 2],
        [3, 4]])

In [39]:
z = y.numpy()
z

array([[1, 2],
       [3, 4]])

In [1]:
y 

NameError: name 'y' is not defined

### bmm (batch matrix multiply)

In [34]:
batch1 = torch.randn(10, 3, 4)
batch2 = torch.randn(10,4,3)
res = torch.bmm(batch1,batch2)

In [36]:
res.shape

torch.Size([10, 3, 3])

### input pipline 

In [125]:
train_dataset = torchvision.datasets.CIFAR10(root='../../data/',
                                             train=True, 
                                             transform=transforms.ToTensor(),
                                             download=True)


Files already downloaded and verified


In [126]:
image , label = train_dataset[0]

In [131]:
image.size(), label

(torch.Size([3, 32, 32]), 6)

In [132]:
train_loader = torch.utils.data.DataLoader(dataset=train_dataset, batch_size = 64 , shuffle = True )


In [133]:
data_iter = iter(train_loader)

In [134]:
images , labels = data_iter.next()

In [135]:
for images , labels in train_loader:
    pass 


### 预训练模型

In [72]:
resnet = torchvision.models.resnet18(pretrained=True)

Downloading: "https://download.pytorch.org/models/resnet18-5c106cde.pth" to /Users/mac/.torch/models/resnet18-5c106cde.pth
46827520.0 bytes


In [80]:
type(next(resnet.parameters()))

torch.nn.parameter.Parameter

In [81]:
next(resnet.parameters()).shape 

torch.Size([64, 3, 7, 7])

In [73]:
images = torch.randn(64, 3, 224, 224)

In [74]:
outputs = resnet(images) # 输出等于输入经过模型