In [8]:
import torch 
import torchvision
import torch.nn as nn
import numpy as np
import torchvision.transforms as transforms

###  example 1
$y = wX + b$

In [48]:
x = torch.tensor(1.0 )
w = torch.tensor(2.0 ,requires_grad = True)
b = torch.tensor(3.0 ,requires_grad = True)

In [49]:
x

tensor(1.)

In [50]:
y = w * x  + b 

In [51]:
y.backward()
x.grad , w.grad , b.grad 

(None, tensor(1.), tensor(1.))

### example 2 

In [52]:
x = torch.randn(10,3) #定义输入
y = torch.randn(10,2) #label

In [53]:
x

tensor([[-1.3365,  0.6173, -0.6000],
        [-1.9425, -2.0253,  1.0767],
        [ 0.5417,  2.2370,  0.6753],
        [-0.7674, -1.6663, -0.3089],
        [-0.0922, -1.3719,  0.6936],
        [ 0.4994,  0.8899,  0.5333],
        [ 0.5662,  0.7245,  0.6402],
        [ 1.1952, -0.0436, -0.9510],
        [-0.9468,  0.9151, -2.2508],
        [-0.4694, -1.6142, -0.3618]])

In [54]:
x.transpose(0,1)

tensor([[-1.3365, -1.9425,  0.5417, -0.7674, -0.0922,  0.4994,  0.5662,  1.1952,
         -0.9468, -0.4694],
        [ 0.6173, -2.0253,  2.2370, -1.6663, -1.3719,  0.8899,  0.7245, -0.0436,
          0.9151, -1.6142],
        [-0.6000,  1.0767,  0.6753, -0.3089,  0.6936,  0.5333,  0.6402, -0.9510,
         -2.2508, -0.3618]])

In [55]:
linear = nn.Linear(3,2) #创建一个全联接的网络 ，有初始化的w 和 b 
linear.weight  , linear.bias 

(Parameter containing:
 tensor([[-0.4331,  0.2033,  0.4665],
         [ 0.4696,  0.3055, -0.3316]], requires_grad=True),
 Parameter containing:
 tensor([0.2380, 0.5537], requires_grad=True))

In [56]:
criterion = nn.MSELoss()   #定义损失函数
optimizer = torch.optim.SGD(linear.parameters(), lr=0.01) # 随机梯度下降

In [57]:
pred = linear(x) # 预测值 等于输入值经过网络 

In [49]:
loss = criterion(pred,y)   # 预测值与真实值计算误差
np.sqrt(loss.item()) 

0.80408243930732815

In [50]:
type(loss)

torch.Tensor

In [51]:
loss.backward() #反向传播 

In [52]:
linear.weight.grad  , linear.bias.grad  # 计算梯度 

(tensor([[-0.0632, -0.6091, -0.2261],
         [ 0.2343,  0.1718, -0.0515]]), tensor([0.0477, 0.2120]))

In [53]:
optimizer.step() # 一次随机梯度下降  ，权值更新

In [54]:
linear.weight  

Parameter containing:
tensor([[-0.1362, -0.0805,  0.2744],
        [ 0.5351,  0.1266, -0.1395]], requires_grad=True)

In [59]:
pred = linear(x) # 重新预测
loss = criterion(pred,y) # 重新计算误差
np.sqrt(loss.item()) #误差降低 

0.80062243119482102

### example 3

$$
\left[
\begin{matrix}
1 & 2 \\
3 & 3 \\
\end{matrix}
\right]
$$

In [58]:
x = np.array([[1,2],[3,4]])

In [59]:
y = torch.from_numpy(x)
y

tensor([[1, 2],
        [3, 4]])

In [60]:
z = y.numpy()
z

array([[1, 2],
       [3, 4]])

In [61]:
y 

tensor([[1, 2],
        [3, 4]])

### bmm (batch matrix multiply)

In [62]:
batch1 = torch.randn(10, 3, 4)
batch2 = torch.randn(10,4,3)
res = torch.bmm(batch1,batch2)

In [63]:
res.shape

torch.Size([10, 3, 3])

### input pipline 

In [64]:
train_dataset = torchvision.datasets.CIFAR10(root='../../data/',
                                             train=True, 
                                             transform=transforms.ToTensor(),
                                             download=True)


0it [00:00, ?it/s]

  1%|▏         | 2244608/170498071 [00:08<04:59, 562499.75it/s]

KeyboardInterrupt: 

In [126]:
image , label = train_dataset[0]

In [131]:
image.size(), label

(torch.Size([3, 32, 32]), 6)

In [132]:
train_loader = torch.utils.data.DataLoader(dataset=train_dataset, batch_size = 64 , shuffle = True )


In [133]:
data_iter = iter(train_loader)

In [134]:
images , labels = data_iter.next()

In [135]:
for images , labels in train_loader:
    pass 


### 预训练模型

In [72]:
resnet = torchvision.models.resnet18(pretrained=True)

Downloading: "https://download.pytorch.org/models/resnet18-5c106cde.pth" to /Users/mac/.torch/models/resnet18-5c106cde.pth
46827520.0 bytes


In [80]:
type(next(resnet.parameters()))

torch.nn.parameter.Parameter

In [81]:
next(resnet.parameters()).shape 

torch.Size([64, 3, 7, 7])

In [73]:
images = torch.randn(64, 3, 224, 224)

In [74]:
outputs = resnet(images) # 输出等于输入经过模型