In [9]:
import torch 
import torch.nn as nn
import numpy as np

###  example 1
$y = wX + b$

In [10]:
x = torch.tensor(1.0 )
w = torch.tensor(2.0 ,requires_grad = True)
b = torch.tensor(3.0 ,requires_grad = True)

In [11]:
x

tensor(1.)

In [12]:
y = w * x  + b 

In [13]:
y.backward()
x.grad , w.grad , b.grad 

(None, tensor(1.), tensor(1.))

### example 2 

In [14]:
x = torch.randn(10,3) #定义输入
y = torch.randn(10,2) #label

In [15]:
x

tensor([[ 1.3813, -0.2674, -1.4839],
        [-0.0519,  1.5469, -0.8521],
        [ 0.6916, -0.9706, -0.1637],
        [ 0.6132,  0.4132, -0.4605],
        [ 1.9149,  1.1381, -0.0915],
        [ 0.7834,  0.4199,  0.6747],
        [ 0.3741,  1.2531,  1.2645],
        [-1.2188, -0.9036,  1.2308],
        [-1.0426,  0.5283,  1.0100],
        [-2.5277,  0.1164,  1.0974]])

In [16]:
x.transpose(0,1)

tensor([[ 1.3813, -0.0519,  0.6916,  0.6132,  1.9149,  0.7834,  0.3741, -1.2188,
         -1.0426, -2.5277],
        [-0.2674,  1.5469, -0.9706,  0.4132,  1.1381,  0.4199,  1.2531, -0.9036,
          0.5283,  0.1164],
        [-1.4839, -0.8521, -0.1637, -0.4605, -0.0915,  0.6747,  1.2645,  1.2308,
          1.0100,  1.0974]])

In [17]:
linear = nn.Linear(3,2) #创建一个全联接的网络 ，有初始化的w 和 b 
linear.weight  , linear.bias 

(Parameter containing:
 tensor([[-0.0126,  0.1540, -0.0428],
         [ 0.2695, -0.3842,  0.4393]], requires_grad=True),
 Parameter containing:
 tensor([0.5049, 0.3219], requires_grad=True))

In [18]:
criterion = nn.MSELoss()   #定义损失函数
optimizer = torch.optim.SGD(linear.parameters(), lr=0.01) # 随机梯度下降

In [19]:
pred = linear(x) # 预测值 等于输入值经过网络 

In [20]:
loss = criterion(pred,y)   # 预测值与真实值计算误差
np.sqrt(loss.item()) 

1.231367237299327

In [21]:
type(loss)

torch.Tensor

In [22]:
loss.backward() #反向传播 

In [23]:
linear.weight.grad  , linear.bias.grad  # 计算梯度 

(tensor([[-0.2665,  0.1405,  0.3579],
         [ 0.2249, -0.4664,  0.3840]]), tensor([0.9724, 0.0023]))

In [24]:
optimizer.step() # 一次随机梯度下降  ，权值更新

In [25]:
linear.weight  

Parameter containing:
tensor([[-0.0100,  0.1526, -0.0464],
        [ 0.2673, -0.3795,  0.4354]], requires_grad=True)

In [26]:
pred = linear(x) # 重新预测
loss = criterion(pred,y) # 重新计算误差
np.sqrt(loss.item()) #误差降低 

1.2249699841928625

### example 3

$$
\left[
\begin{matrix}
1 & 2 \\
3 & 3 \\
\end{matrix}
\right]
$$

In [27]:
x = np.array([[1,2],[3,4]])

In [28]:
y = torch.from_numpy(x)
y

tensor([[1, 2],
        [3, 4]])

In [29]:
z = y.numpy()
z

array([[1, 2],
       [3, 4]])

In [30]:
y 

tensor([[1, 2],
        [3, 4]])

### bmm (batch matrix multiply)

In [31]:
batch1 = torch.randn(10, 3, 4)
batch2 = torch.randn(10,4,3)
res = torch.bmm(batch1,batch2)

In [32]:
res.shape

torch.Size([10, 3, 3])

### input pipline 

In [64]:
train_dataset = torchvision.datasets.CIFAR10(root='../../data/',
                                             train=True, 
                                             transform=transforms.ToTensor(),
                                             download=True)


0it [00:00, ?it/s]

  1%|▏         | 2244608/170498071 [00:08<04:59, 562499.75it/s]

KeyboardInterrupt: 

In [126]:
image , label = train_dataset[0]

In [131]:
image.size(), label

(torch.Size([3, 32, 32]), 6)

In [132]:
train_loader = torch.utils.data.DataLoader(dataset=train_dataset, batch_size = 64 , shuffle = True )


In [133]:
data_iter = iter(train_loader)

In [134]:
images , labels = data_iter.next()

In [135]:
for images , labels in train_loader:
    pass 


### 预训练模型

In [72]:
resnet = torchvision.models.resnet18(pretrained=True)

Downloading: "https://download.pytorch.org/models/resnet18-5c106cde.pth" to /Users/mac/.torch/models/resnet18-5c106cde.pth
46827520.0 bytes


In [80]:
type(next(resnet.parameters()))

torch.nn.parameter.Parameter

In [81]:
next(resnet.parameters()).shape 

torch.Size([64, 3, 7, 7])

In [73]:
images = torch.randn(64, 3, 224, 224)

In [74]:
outputs = resnet(images) # 输出等于输入经过模型