### layer normalization

In [2]:
import torch
import torch.nn as nn 

In [3]:
x = torch.rand(4,3)
x

tensor([[0.2366, 0.6843, 0.1054],
        [0.4602, 0.4148, 0.9294],
        [0.5686, 0.6092, 0.9162],
        [0.9887, 0.5186, 0.1120]])

In [6]:
mean_x = x.mean(-1, keepdim = True) #保持维度依然是2维
mean_x

tensor([[0.3421],
        [0.6014],
        [0.6980],
        [0.5398]])

In [7]:
std_x = x.std(-1, keepdim = True)
std_x

tensor([[0.3035],
        [0.2849],
        [0.1901],
        [0.4388]])

In [21]:
w = nn.Parameter(torch.ones(4,3))
b = nn.Parameter(torch.zeros(4,3))