### layer normalization

In [3]:
import torch
import torch.nn as nn 

In [17]:
x = torch.rand(4,3)
x

tensor([[0.6659, 0.5622, 0.7653],
        [0.3952, 0.3795, 0.6276],
        [0.8789, 0.5203, 0.6595],
        [0.8059, 0.6034, 0.3635]])

In [18]:
mean_x = x.mean(-1, keepdim = True) #保持维度依然是2维
mean_x

tensor([[0.6645],
        [0.4674],
        [0.6863],
        [0.5909]])

In [19]:
std_x = x.std(-1, keepdim = True)
std_x

tensor([[0.1016],
        [0.1389],
        [0.1808],
        [0.2214]])

In [21]:
w = nn.Parameter(torch.ones(4,3))
b = nn.Parameter(torch.zeros(4,3))