In [2]:
import torch
import torch.nn as nn
import torch.nn.functional as F

### What is pytorch ?

In [3]:
x = torch.empty(5,3) #创建一个5*3 的矩阵
x

tensor([[0.0000e+00, 1.5846e+29, 0.0000e+00],
        [1.5846e+29, 5.6052e-45, 0.0000e+00],
        [1.4357e-28,        nan, 3.2231e+08],
        [4.5845e-41, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 7.0065e-45]])

In [8]:
x = torch.rand(4,3 )   # 0～1 之间的数
x

tensor([[0.6819, 0.6869, 0.4024],
        [0.4486, 0.4509, 0.1973],
        [0.4645, 0.8787, 0.6248],
        [0.0226, 0.8369, 0.4315]])

In [6]:
x = torch.zeros(4,3, dtype = torch.long )
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

### 随机数

In [80]:
torch.rand(2,3)  #0~1 之间的随机数

tensor([[0.4948, 0.2249, 0.2364],
        [0.1869, 0.1459, 0.2298]])

In [114]:
train_y = torch.randn( 5, 1)
train_y

tensor([[-0.8252],
        [ 0.2579],
        [ 0.7514],
        [ 0.5426],
        [-0.3009]])

In [117]:
torch.FloatTensor([1,2])

tensor([1., 2.])

In [85]:
torch.LongTensor(10).random_(0, 10) #随机0～10 间的整数

tensor([6, 2, 8, 7, 7, 8, 8, 9, 7, 0])

In [78]:
torch.randint(1, 5, (3,))  #1~5 之间的随机整数

tensor([2, 1, 3])

### 类型转换

In [58]:
cnm = [[_ for _ in range(2)] for _ in range(3) ]
torch.Tensor(cnm)

tensor([[0., 1.],
        [0., 1.],
        [0., 1.]])

### 判断是否有空元素

In [153]:
A = torch.Tensor([1,2,np.nan,np.nan])
torch.isnan(A)

tensor(2)

### 自动求导

In [9]:
from torch import tensor , autograd

In [10]:
x = tensor(1.0)
a = tensor(2.0, requires_grad = True) 
b = tensor(2.0, requires_grad = True)
c = tensor(3.0, requires_grad = True)
y = a**2 * x + b * x + c 
gradients = autograd.grad(y , [a,b,c])
gradients

(tensor(4.), tensor(1.), tensor(1.))

### view 改变矩阵维度
view维度改成开始的，可以复原

In [69]:
a = torch.arange(9)
a.view(-1 ,3)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [71]:
b = torch.rand(4,4)
b.view(2,8) # (行，列) 

tensor([[0.7226, 0.6444, 0.3888, 0.4147, 0.4774, 0.5994, 0.1287, 0.7320],
        [0.8848, 0.9148, 0.7601, 0.1267, 0.7940, 0.6812, 0.7675, 0.6133]])

In [72]:
b.view(2,2,4)

tensor([[[0.7226, 0.6444, 0.3888, 0.4147],
         [0.4774, 0.5994, 0.1287, 0.7320]],

        [[0.8848, 0.9148, 0.7601, 0.1267],
         [0.7940, 0.6812, 0.7675, 0.6133]]])

### permute 交换矩阵的轴

In [120]:
x = torch.rand(2,3,5)
x.permute(2,0,1).shape   # 原本的（2，3，5） 变成 （5，2，3） 

torch.Size([5, 2, 3])

## 矩阵相乘

### mm   ( matrix multip)   
两个二维矩阵相乘

In [14]:
A = torch.arange(4).reshape(2,2)
A

tensor([[0, 1],
        [2, 3]])

In [15]:
B = torch.arange(1,5).reshape(2,2)
B

tensor([[1, 2],
        [3, 4]])

In [16]:
torch.mm(A,B)

tensor([[ 3,  4],
        [11, 16]])

In [18]:
A*B  # 对应元素相乘

tensor([[ 0,  2],
        [ 6, 12]])

## bmm ( batch matrix multip ) 


In [47]:
batch1 = torch.randn(10, 3, 4)
batch2 = torch.randn(10, 4, 5)
res = torch.bmm(batch1, batch2)
res.size()

torch.Size([10, 3, 5])

In [49]:
batch1.size()[0] 

10

#### 用bmm讲两个（ 2 ，10） 的矩阵，变成一个( 2 ,1 )的矩阵

In [21]:
A = torch.LongTensor(2,10).random_(1,10)
print(A)
B = torch.LongTensor(2,10).random_(1,10)
print(B)

tensor([[5, 3, 1, 6, 4, 4, 6, 9, 7, 1],
        [8, 8, 5, 7, 6, 2, 6, 1, 6, 7]])
tensor([[9, 9, 9, 5, 8, 3, 9, 8, 9, 1],
        [3, 6, 4, 6, 7, 2, 2, 8, 6, 4]])


In [20]:
torch.bmm(A.view(2, 1, 10 ), B.view(2,10,1))

tensor([[[193]],

        [[234]]])

###  spmm (sparse)

In [25]:
a_sparse = torch.sparse.FloatTensor(2, 2).to_dense()
a_sparse

tensor([[0., 0.],
        [0., 0.]])

In [26]:
b= torch.Tensor([[1,2],[3,4]])

In [27]:
torch.spmm(a_sparse,b)

tensor([[0., 0.],
        [0., 0.]])

In [59]:
a_sparse = torch.sparse.FloatTensor(100, 100).to_dense()
a_sparse.sum()

tensor(0.)

### matmul (A,B) 
A可以是任意维， B必须是2维

In [56]:
A = torch.Tensor(6,4,5,2)
B = torch.Tensor(2,3)
torch.matmul(A,B).shape

torch.Size([6, 4, 5, 3])

In [55]:
A = torch.Tensor(5,5)
B = torch.Tensor(3,5,6)
torch.matmul(A,B).shape 

torch.Size([3, 5, 6])

### cat  拼接矩阵 

In [155]:
A = torch.Tensor( [[0.1 , 0.9], [0.2,0.8]] )
print(A)
B = torch.Tensor([[0.2 , 0.8], [0.1,0.9] ])
print(B)

tensor([[0.1000, 0.9000],
        [0.2000, 0.8000]])
tensor([[0.2000, 0.8000],
        [0.1000, 0.9000]])


In [156]:
torch.cat((A,B), 1 ) #  0 为 按行， 1 为 按列 ， -1为按最后一维的元素

tensor([[0.1000, 0.9000, 0.2000, 0.8000],
        [0.2000, 0.8000, 0.1000, 0.9000]])

### expand

In [133]:
a = torch.Tensor([[0,1,2],[3,4,5],[6,7,8]])
a.unsqueeze_(-1)
print(a.shape)
a = a.expand(3,3,10)
a.shape 

torch.Size([3, 3, 1])


torch.Size([3, 3, 10])

In [136]:
graph = torch.rand(2,2)
graph.unsqueeze_(-1)
graph = graph.expand(2,2,3)
graph

tensor([[[0.1876, 0.1876, 0.1876],
         [0.6984, 0.6984, 0.6984]],

        [[0.3778, 0.3778, 0.3778],
         [0.0158, 0.0158, 0.0158]]])

In [137]:
graph = torch.Tensor([[1,2],[3,4]])
graph.unsqueeze(-1)
print(graph)
graph = graph.repeat(2,1,1)
graph

tensor([[1., 2.],
        [3., 4.]])


tensor([[[1., 2.],
         [3., 4.]],

        [[1., 2.],
         [3., 4.]]])

### repeat

In [87]:
graph = torch.rand(4,4)
graph.repeat(2,1).shape  #对应维度乘以repeat的数值

torch.Size([8, 4])

### unsqueeze   , (4) -> (4,1)   增加一个维度1  ， 或者squeeze()将一个为1 的维度消掉

In [128]:
a = torch.Tensor([1,2,3])
a.shape

torch.Size([3])

In [122]:
a.unsqueeze(0).shape  # 增加一个横轴的维度

torch.Size([1, 3])

In [130]:
a.unsqueeze(1).shape 

torch.Size([3, 1])

In [144]:
x = torch.Tensor( [[1,2]]  ) # 第一个维度只有一个元素 ，等于就是 之后维度的这个元素
print(x.shape)
x = x.squeeze(0) 
print(x.shape)

torch.Size([1, 2])
torch.Size([2])


### numpy 写法 newaxis

In [124]:
import numpy as np 
a = np.array([1,2])
a.shape

(2,)

In [127]:
a[ : , np.newaxis].shape

(2, 1)

### where  对tensor 元素筛选

In [98]:
cluster = torch.rand(4,2)

In [99]:
a = torch.ones(4,2)
b = torch.zeros(4,2)

In [100]:
torch.where( cluster>0.5 , a , b)

tensor([[1., 0.],
        [1., 1.],
        [0., 1.],
        [0., 1.]])

### nonzero 打印出所有非0元素的index

In [93]:
adj = torch.Tensor([[1,0], [0,6]])
adj 

tensor([[1., 0.],
        [0., 6.]])

In [92]:
adj.nonzero() 

tensor([[0, 0],
        [1, 1]])