In [19]:
import os  
import sys
import numpy as np
import matplotlib
import scipy
import matplotlib.pyplot as plt
from sklearn import feature_extraction  
from sklearn.feature_extraction.text import TfidfTransformer  
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import HashingVectorizer
import lda

In [20]:
#存储读取语料 一行预料为一个文档 
text_all  = ['刘',
 '选中一根线，往下滑，看是什么 \u200b\u200b\u200b\u200b',
 '有一只会宠你的橘子是什么体验！！！ http://t.cn/A6zTInYp \u200b\u200b\u200b',
 '#BrightWin[超话]# 💎#泰剧只因我们天生一对[超话]# \n\n200318｜BrightWin❤️\nⒸⓇ:  backaof TW\n\n大意：\n一个人想看电视剧 🙄\n一个人想吃东西😬\n你可以在这张照片看到这些',
  '\n\n☀️：我很满意',
  '\n\n翻译：Yusa 🇹🇭\n________',
 '有一只会宠你的橘子是什么体验！！！ http://t.cn/A6zTInYp \u200b\u200b\u200b',
]


In [22]:
len(text_all)

7

In [23]:
#将文本中的词语转换为词频矩阵 矩阵元素a[i][j] 表示j词在i类文本下的词频
vectorizer = CountVectorizer()
print(vectorizer)

CountVectorizer(analyzer='word', binary=False, decode_error='strict',
                dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
                lowercase=True, max_df=1.0, max_features=None, min_df=1,
                ngram_range=(1, 1), preprocessor=None, stop_words=None,
                strip_accents=None, token_pattern='(?u)\\b\\w\\w+\\b',
                tokenizer=None, vocabulary=None)


In [16]:
X = vectorizer.fit_transform(text_all)
analyze = vectorizer.build_analyzer()
weight = X.toarray()
print(len(weight))
print((weight[:5, :5]))

7
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 1 0 0]
 [1 0 0 1 2]
 [0 0 0 0 0]]


In [18]:
#LDA算法
model = lda.LDA(n_topics=2, n_iter=500, random_state=1)
model.fit(np.asarray(weight))     # model.fit_transform(X) is also available
topic_word = model.topic_word_    # model.components_ also works

NameError: name 'lda' is not defined