### 线性代数库  linalg   ( linear algebra ) 

In [6]:
import numpy as np 
from numpy import linalg

In [11]:
linalg.det(m)

-229.99999999999983

In [7]:
a = np.array([1,2,3])
a_mat = np.mat(a)
### 将array类型转换成矩阵类型 
a_mat.I   #矩阵求逆 

m = np.matrix([[1,-2,3],[0,4,5],[7,8,-9]])

## 行列式 determinant 
linalg.det(m)

## 特征值 eigenvalues
linalg.eigvals(m)

array([-13.11474312,   2.75956154,   6.35518158])

In [12]:
x = np.diag((1,2,3)) #对角阵
x

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [14]:
a = linalg.eigvals(x) # 特征值
a

array([1., 2., 3.])

In [5]:
linalg.eig(x) #特征向量

(array([1., 2., 3.]),
 array([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]))