## numpy基础

ndarray 多维数组，能向量化数据

In [2]:
import numpy as np 

In [70]:
arr = np.arange(10)
arr,type(arr)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), numpy.ndarray)

In [74]:
num_list = list(arr)
num_list

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [79]:
### array 和 list 转换
num_list = [1,2,3]
np.array(num_list)

array([1, 2, 3])

### 数据类型与维度

In [95]:
arr = np.arange(10)
arr.ndim , arr.dtype

(1, dtype('int64'))

In [97]:
# max
np.max(arr)

9

In [98]:
# mean 
np.mean(arr)

4.5

#### astype 更改数组中的数据类型

In [90]:
arr.astype(np.str)

array(['0', '1', '2', '3', '4', '5', '6', '7', '8', '9'], dtype='<U21')

#### reshape 更改维度

In [105]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [104]:
np.mean(a,axis=0)

array([4., 5., 6., 7.])

In [16]:
a = np.arange(12).reshape(-1,2)  # 如果让numpy自己算就用-1 
a 

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

### mean

In [99]:
b = np.mean(a,axis = 0)
b = np.mean(b, axis =0 )
b.shape

(768,)

### 切片

In [107]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a[0][2],a[0,2])
print(a[:2,1:])

3 3
[[2 3]
 [5 6]]


In [21]:
x = np.linspace(1,2,10) #在1到2之间均匀的取10个数
x

array([ 1.        ,  1.11111111,  1.22222222,  1.33333333,  1.44444444,
        1.55555556,  1.66666667,  1.77777778,  1.88888889,  2.        ])

In [22]:
b = np.array([1,2,3])
np.tile(b,(2,3))

array([[1, 2, 3, 1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3, 1, 2, 3]])

### 初始化数组

In [23]:
n = np.random.randn(3,4)    # 得到3*4维的随机矩阵 ，数据都是标准正态分布的（均值为0，标准差为1） 
n

array([[ 1.85601563, -1.05785697,  0.57271205,  0.59534674],
       [ 0.76889725, -1.73708089, -1.0966923 , -0.71822735],
       [-1.2023417 , -2.10544641,  0.75870694, -0.71676642]])

In [24]:
np.random.normal(100,size=(4,4)) #正太分布 以100为中心

array([[  98.94101228,   99.54341492,   96.89953115,   99.0758328 ],
       [  99.8553165 ,   99.65874299,   99.12449241,  100.11162186],
       [ 100.32648206,   99.65126194,  100.27064406,  102.15100684],
       [  99.01650278,   99.70725933,  100.0357265 ,  100.80366263]])

In [25]:
n.transpose(), n.T 

(array([[ 1.85601563,  0.76889725, -1.2023417 ],
        [-1.05785697, -1.73708089, -2.10544641],
        [ 0.57271205, -1.0966923 ,  0.75870694],
        [ 0.59534674, -0.71822735, -0.71676642]]),
 array([[ 1.85601563,  0.76889725, -1.2023417 ],
        [-1.05785697, -1.73708089, -2.10544641],
        [ 0.57271205, -1.0966923 ,  0.75870694],
        [ 0.59534674, -0.71822735, -0.71676642]]))

In [26]:
a = np.zeros((2,3,4,5))
a

array([[[[ 0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.]],

        [[ 0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.]],

        [[ 0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.]]],


       [[[ 0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.]],

        [[ 0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.]],

        [[ 0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.]]]])

- 四维数组（2*3*4*5）由2个三维数组（3 * 4 * 5）组成
- 每个三维数组由三个两维数组构成。
- 每个两维数组由4个一维数组构成
- 每个一维数组由5个数构成

### unique 去重

In [63]:
# 去重 ，相当于set并排序
a = np.array([2,3,4,3,3,2,1])
np.unique(a) 

array([1, 2, 3, 4])

### replace 

In [2]:
import numpy as np

In [6]:
# 可以 指定替换的个数（ 默认全部替换） 
string_array = ['s','ss','a']
np.core.defchararray.replace(string_array, 's', 'a',count=1)

array(['a', 'as', 'a'], dtype='<U2')

In [7]:
# numpy 广播替换字符
nums =np.array( ['asdf','adf','asdf'])
nums_2 = np.core.defchararray.replace(nums,'a','b')
nums_2

array(['bsdf', 'bdf', 'bsdf'], dtype='<U4')

In [8]:
#将字符型数据的双引号去掉 
nums_arr = np.array(['200','300','400'])
nums_arr2 = np.core.defchararray.replace(nums_arr,"'"," ")
nums_arr2

array(['200', '300', '400'], dtype='<U3')

### pad
在数组的边界周围添加填充.
可以在卷积操作中，保持输出和输入的格式一致

In [9]:
a1 = np.array([1,2,3])
a2 = np.pad(a1,(2,10) ) # 前面加2个0， 后面加10个0

In [10]:
a2

array([0, 0, 1, 2, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### fill
将array的所有元素设置为指定的标量， 直接修改array的内容， 而不是返回一个新的数组

In [15]:
a1 = np.array([1,2,3])
a1.fill(1)
a1

array([1, 1, 1])

### numpy 读文件
读取后的类型是一个array

loadtxt:
- dtype : 指定数据类型
- delimiter 分割符
- skiprows 跳过行
- usecols=(0, 2) 只用 0,2 两列


In [22]:
data_file = 'Iris.txt'

In [36]:
data_arr = np.loadtxt(data_file,delimiter=',', dtype = str , skiprows = 1)  # skiprow=1 跳过第一行

In [37]:
data_arr[:5]

array([['4.9', '3.0', '1.4', '0.2', 'Iris-setosa'],
       ['4.7', '3.2', '1.3', '0.2', 'Iris-setosa'],
       ['4.6', '3.1', '1.5', '0.2', 'Iris-setosa'],
       ['5.0', '3.6', '1.4', '0.2', 'Iris-setosa'],
       ['5.4', '3.9', '1.7', '0.4', 'Iris-setosa']], dtype='<U15')

In [ ]:
#  存储文件
np.savetxt('log1000.txt',c) # c 为要存的数组

numpy.savetxt("foo.csv", a, delimiter=",")  # save csv

###  广播运算
numpy的广播，能够对每个元素进行同样的运算

In [31]:
arr = np.array([[1,2,3],[4,5,6]])
arr.sum()   # 计算所有元素之和

21

In [32]:
# 将一个标量赋值给一个数组切片时，该值会自动广播到整个选区
arr = np.arange(10)
arr[5:8] = 666
arr

array([  0,   1,   2,   3,   4, 666, 666, 666,   8,   9])

In [33]:
arr*arr  # 元素对应相乘

array([     0,      1,      4,      9,     16, 443556, 443556, 443556,
           64,     81])

In [34]:
np.sqrt(arr)

array([  0.        ,   1.        ,   1.41421356,   1.73205081,
         2.        ,  25.8069758 ,  25.8069758 ,  25.8069758 ,
         2.82842712,   3.        ])

- array 数组使你不用进行循环就能进行批量运算。
- 对 array数组直接使用运算符，相当于所有元素对应进行运算。

In [35]:
arr_1 = np.array([[1,2],[3,4]])
arr_2 = np.array([[2,3],[4,5]])
print(np.dot(arr_1,arr_2)) # 计算点积
print(arr_1*arr_2)  #矩阵中的元素对应相乘

[[10 13]
 [22 29]]
[[ 2  6]
 [12 20]]


### 切片

In [36]:
arr_slice = arr[5:8]
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

array类型被切片后不会赋值，只保留一份数据，广播给多个元素

In [37]:
arr = np.random.rand(3,4)
print(arr,'\n')
print(arr[[True,False,True]])  
#用布尔型列表切片数组  取三行中的第一行和第三行，不要第二行。

[[ 0.824628    0.6455714   0.21855941  0.83252716]
 [ 0.38903696  0.59376337  0.61096116  0.19810541]
 [ 0.36557158  0.57806735  0.52523974  0.68174309]] 

[[ 0.824628    0.6455714   0.21855941  0.83252716]
 [ 0.36557158  0.57806735  0.52523974  0.68174309]]


### 筛选数据

In [38]:
arr[arr<0.5] =  0
arr

array([[ 0.824628  ,  0.6455714 ,  0.        ,  0.83252716],
       [ 0.        ,  0.59376337,  0.61096116,  0.        ],
       [ 0.        ,  0.57806735,  0.52523974,  0.68174309]])

按条件批量改变数组的值

In [39]:
arr = np.random.rand(4,4)
print(arr)
np.where(arr>0.5,'>0.5','<0.5')

[[ 0.87147676  0.6042865   0.29484298  0.87922619]
 [ 0.36278285  0.30940235  0.47299947  0.54079367]
 [ 0.10422901  0.80316375  0.50438807  0.00482028]
 [ 0.79729648  0.47387168  0.65253179  0.59221817]]


array([['>0.5', '>0.5', '<0.5', '>0.5'],
       ['<0.5', '<0.5', '<0.5', '>0.5'],
       ['<0.5', '>0.5', '>0.5', '<0.5'],
       ['>0.5', '<0.5', '>0.5', '>0.5']],
      dtype='<U4')

In [40]:
np.where(arr>0.5, '>0.5' ,arr)

array([['>0.5', '>0.5', '0.2948429802481344', '>0.5'],
       ['0.3627828515144901', '0.309402345154861', '0.47299946851109875',
        '>0.5'],
       ['0.10422900705537774', '>0.5', '>0.5', '0.004820284374500994'],
       ['>0.5', '0.473871679187023', '>0.5', '>0.5']],
      dtype='<U32')

### 拉平数据 flatten

In [109]:
a = np.array([[1,2], [3,4]])  
a.flatten() # 拉平

array([1, 2, 3, 4])

In [110]:
a=np.random.randint(1,10,15).reshape(3,5)
a_item , a_nums = np.unique(a, return_counts=True)
a, a_item , a_nums 
#统计每个元素出现的次数

(array([[5, 6, 4, 8, 7],
        [4, 2, 2, 2, 9],
        [8, 5, 1, 1, 9]]),
 array([1, 2, 4, 5, 6, 7, 8, 9]),
 array([2, 3, 2, 2, 1, 1, 2, 2]))

### ravel , flatten
- ravel 和 flatten 都是将多维数组展平为一维数组。
- 不同的是： ravel ，返回原数组的view。修改会影响原数组
- flatten 返回原数组的copy ， 这意味着修改展平后的数组不会影响原数组。
- flatten() 通常比 ravel() 慢，因为它需要复制数据。



In [19]:
arr = np.arange(12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [25]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [24]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

### concatenate 

In [3]:
### concatenate 
a = np.array([[0,0]])
b = np.array([[5,6]])
np.concatenate((a,b))

array([[0, 0],
       [5, 6]])

In [16]:
res.shape

(1, 176)

In [11]:
a = np.random.rand(1,7)
b = np.random.rand(1,7)

In [13]:
c = np.concatenate((a,b))
c.shape

(2, 7)

In [14]:
c = np.concatenate((a,b),axis=1)
c.shape

(1, 14)

### bincount

In [62]:
# bincount 计数
num_array = np.array([1,2,2,3,3,3,4,4])
np.bincount(num_array)

array([0, 1, 2, 3, 2])

In [15]:
# 保留小数 around
np.around([0.371231, 1.6412313], decimals=2)

array([0.37, 1.64])