### random walk
从0开始随机向两边走

In [1]:
import random
# 0或1 的随机数
random.randint(0,1)

1

In [22]:
# 得到 -1或1 的随机数
2*random.randint(0,1)-1

1

In [37]:
position = 0 
for i in range(10):
    position += 2*random.randint(0,1)-1
    print(position)

1
0
-1
-2
-3
-4
-5
-6
-7
-8


In [38]:
class RandomWalker:
    def __init__(self):
        self.position = 0
    def walk(self,n):
        for i in range(n):
            yield self.position
            self.position += 2*random.randint(0,1)-1

In [39]:
walker = RandomWalker()
wark = [position for position in walker.walk(100)]

### 向量化 vectorized

In [44]:
from itertools import accumulate

In [57]:
[0] + list(accumulate(random.choices([-1,+1], k=10)))

[0, 1, 2, 3, 4, 5, 4, 5, 6, 7, 6]

#### use numpy 

In [2]:
import numpy as np 
steps = np.random.choice([-1,1],10)

In [3]:
np.cumsum(steps)

array([-1, -2, -1, -2, -3, -4, -5, -6, -7, -6])

In [4]:
Z = np.ones(4*1000000, np.float32)

In [13]:
timeit("Z.view(np.float16)[...] = 0", globals())

58.7 ns ± 0.638 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [12]:
timeit("Z.view(np.int8)[...] = 0", globals())

58.4 ns ± 0.406 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


In [14]:
z = np.arange(9).reshape(3,3).astype(np.int16)

In [19]:
z.itemsize, z.shape, z.ndim

(2, (3, 3), 2)

In [20]:
# 2 bytes (int16) : itemsize =2 

In [22]:
Z = np.arange(9).reshape(3,3).astype(np.int16)

In [23]:
Z[1,1].tobytes()

b'\x04\x00'

In [25]:
 Z.strides[1]

2

In [32]:
z = np.zeros(9)


In [33]:
z_view = z[:3]
z_view

array([0., 0., 0.])

In [35]:
z_view[...] = 1

In [36]:
z 

array([1., 1., 1., 0., 0., 0., 0., 0., 0.])