In [4]:
import torch

In [10]:
x = torch.Tensor(2,4) # 2*4 dim matrix

In [8]:
x

tensor([[0.0000e+00, 1.0842e-19, 0.0000e+00, 1.0842e-19],
        [9.8091e-45, 0.0000e+00, 0.0000e+00, 0.0000e+00]])

In [16]:
torch.mv(x,torch.rand(4)) # 2*4 , 4*1 ->2*1

tensor([7.6359e-20, 2.8026e-45])

In [9]:
type(x), x.type(), x.dtype

(torch.Tensor, 'torch.FloatTensor', torch.float32)

In [15]:
l = [[1,2,3],[4,5,6],[7,8,9]]
x = torch.tensor(l)
x

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [18]:
x[0][2] = 99

In [19]:
x

tensor([[ 1,  2, 99],
        [ 4,  5,  6],
        [ 7,  8,  9]])

### create tensor
- torch.zeros()
- torch.ones()
- torch.eye()
- torch.rand() 生成 0-1的随机数
- torch.randn() 服从标准正态分布的随机数
- torch.arange()
- torch.from_numpy()

In [22]:
torch.arange(1,10)

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

### cat chunk view
cat 
chunk

### math function
- add
- mul
- div
- fmod
- abs
- ceil
- floor 
- clamp
- round
- frac
- neg
- reciprocal 倒数
- log
- pow
- exp
- sigmod
- sign
- sqrt
- dist
- mean
- norm
- prod
- sum
- max
- min 

In [4]:
x.norm()

tensor(0.)

In [7]:
x = torch.rand((2,3))
x

tensor([[0.5424, 0.6884, 0.0708],
        [0.8332, 0.9491, 0.3467]])

In [8]:
x.reciprocal()

tensor([[ 1.8436,  1.4526, 14.1237],
        [ 1.2002,  1.0536,  2.8840]])

In [10]:
x.norm()  

tensor(1.5774)

In [9]:
x.dist()

TypeError: dist() missing 1 required positional arguments: "other"

In [43]:
x.clamp(2)

tensor([[2., 2., 2.],
        [2., 2., 2.]])

### 线性代数运算
- dot 
- mm
- mv 
- bmm
- inverse
- eig
- ger