### numpy基础数据类型

In [1]:
import numpy as np 
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [65]:
b = np.arange(12).reshape(3,4)
print(type(b),",",b.dtype)
print(b.ndim)
a = np.array(['a','b'])
b = b.astype(a.dtype)
b

<class 'numpy.ndarray'> , int64
2


array([['0', '1', '2', '3'],
       ['4', '5', '6', '7'],
       ['8', '9', '1', '1']],
      dtype='<U1')

astype 将数组中的所有元素都转换类型


In [29]:
n = np.random.randn(3,4)
n

array([[-0.04597381,  0.32242662, -0.57614437,  0.17627013],
       [-0.97451579,  0.13959943, -0.39028816,  0.24453139],
       [-1.75923284,  0.74801131,  1.65071624, -1.02967444]])

In [20]:
n.transpose(), n.T

(array([[ 0.45487349,  0.0554693 , -0.39843609],
        [-0.66038429,  1.66715374,  0.02092748],
        [-0.99903326, -0.35461257, -1.40561493],
        [-0.96890781, -1.45143509,  0.19172215]]),
 array([[ 0.45487349,  0.0554693 , -0.39843609],
        [-0.66038429,  1.66715374,  0.02092748],
        [-0.99903326, -0.35461257, -1.40561493],
        [-0.96890781, -1.45143509,  0.19172215]]))

In [19]:
b = np.array([1,2,3])
np.tile(b,(2,3))

array([[1, 2, 3, 1, 2, 3, 1, 2, 3],
       [1, 2, 3, 1, 2, 3, 1, 2, 3]])

In [25]:
a = np.array([1,2,3])
np.mat(a)

matrix([[1, 2, 3]])

In [112]:
a = np.zeros((2,3,4,5))
a

array([[[[ 0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.]],

        [[ 0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.]],

        [[ 0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.]]],


       [[[ 0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.]],

        [[ 0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.]],

        [[ 0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.],
         [ 0.,  0.,  0.,  0.,  0.]]]])

- 四维数组（2*3*4*5）由2个三维数组（3*4*5）组成
- 每个三维数组由三个两维数组构成。
- 每个两维数组由4个一维数组构成
- 每个一维数组由5个数构成

In [119]:
np.random.normal(100,size=(4,4)) #正太分布

array([[  99.70796109,  101.39024909,   99.95765084,  100.45697645],
       [ 101.72367725,   99.35734083,  100.67197091,  101.63844955],
       [  99.49723991,   99.50202434,  100.38868166,   99.70815517],
       [  99.71561743,   99.58210338,   98.96371773,   98.95346093]])

In [131]:
a = np.array([2,3,4,3,3,2,1])
np.unique(a)

array([1, 2, 3, 4])

相当于set并排序

###  运算

In [142]:
arr = np.array([[1,2,3],[4,5,6]])
arr.sum()

21

In [140]:
arr*arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [116]:
np.sqrt(arr)

array([[ 1.        ,  1.41421356,  1.73205081],
       [ 2.        ,  2.23606798,  2.44948974]])

- array 数组使你不用进行循环就能进行批量运算。
- 对 array数组直接使用运算符，相当于所有元素对应进行运算。

In [134]:
arr_1 = np.array([[1,2],[3,4]])
arr_2 = np.array([[2,3],[4,5]])
np.dot(arr_1,arr_2)

array([[10, 13],
       [22, 29]])

### 切片

In [78]:
arr = np.arange(10)
arr[5:8] = 666
arr

array([  0,   1,   2,   3,   4, 666, 666, 666,   8,   9])

将一个标量赋值给一个数组切片时，该值会自动广播到整个选区。


In [81]:
arr_slice = arr[5:8]
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

array类型被切片后不会赋值，只保留一份数据。

In [90]:
arr_2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2[0][2],arr_2[0,2])
print(arr_2[:2,1:])


3 3
[[2 3]
 [5 6]]


In [100]:
arr = np.random.rand(3,4)
print(arr)
print arr[[True,False,True]]

[[ 0.56323997  0.31354     0.45216106  0.58065841]
 [ 0.95175952  0.08728083  0.39392828  0.7460041 ]
 [ 0.72294529  0.48654886  0.0719934   0.9817884 ]]


array([[ 0.56323997,  0.31354   ,  0.45216106,  0.58065841],
       [ 0.72294529,  0.48654886,  0.0719934 ,  0.9817884 ]])

用布尔型列表切片数组

In [103]:
arr[arr<0.5] =  0
arr

array([[ 0.56323997,  0.        ,  0.        ,  0.58065841],
       [ 0.95175952,  0.        ,  0.        ,  0.7460041 ],
       [ 0.72294529,  0.        ,  0.        ,  0.9817884 ]])

按条件批量改变数组的值

In [128]:
arr = np.random.rand(4,4)
print(arr)
np.where(arr>0.5,'>0.5','<0.5')

[[ 0.35161293  0.66494179  0.41155585  0.85757453]
 [ 0.30659718  0.0624959   0.4411294   0.03837504]
 [ 0.95619742  0.61148262  0.53340008  0.33620816]
 [ 0.7072329   0.97455356  0.65200832  0.23953566]]


array([['<0.5', '>0.5', '<0.5', '>0.5'],
       ['<0.5', '<0.5', '<0.5', '<0.5'],
       ['>0.5', '>0.5', '>0.5', '<0.5'],
       ['>0.5', '>0.5', '>0.5', '<0.5']],
      dtype='<U4')

In [129]:
np.where(arr>0.5, '>0.5' ,arr)

array([['0.35161292818193013', '>0.5', '0.4115558545973588', '>0.5'],
       ['0.30659718035525596', '0.06249589688319568',
        '0.44112939891558245', '0.03837503995453129'],
       ['>0.5', '>0.5', '>0.5', '0.3362081630954874'],
       ['>0.5', '>0.5', '>0.5', '0.23953565562509838']],
      dtype='<U32')

In [147]:
arr_file = np.loadtxt('Iris.txt',dtype= str)
arr_file


array(['5.1,3.5,1.4,0.2,Iris-setosa', '4.9,3.0,1.4,0.2,Iris-setosa',
       '4.7,3.2,1.3,0.2,Iris-setosa', '4.6,3.1,1.5,0.2,Iris-setosa',
       '5.0,3.6,1.4,0.2,Iris-setosa', '5.4,3.9,1.7,0.4,Iris-setosa',
       '4.6,3.4,1.4,0.3,Iris-setosa', '5.0,3.4,1.5,0.2,Iris-setosa',
       '4.4,2.9,1.4,0.2,Iris-setosa', '4.9,3.1,1.5,0.1,Iris-setosa',
       '5.4,3.7,1.5,0.2,Iris-setosa', '4.8,3.4,1.6,0.2,Iris-setosa',
       '4.8,3.0,1.4,0.1,Iris-setosa', '4.3,3.0,1.1,0.1,Iris-setosa',
       '5.8,4.0,1.2,0.2,Iris-setosa', '5.7,4.4,1.5,0.4,Iris-setosa',
       '5.4,3.9,1.3,0.4,Iris-setosa', '5.1,3.5,1.4,0.3,Iris-setosa',
       '5.7,3.8,1.7,0.3,Iris-setosa', '5.1,3.8,1.5,0.3,Iris-setosa',
       '5.4,3.4,1.7,0.2,Iris-setosa', '5.1,3.7,1.5,0.4,Iris-setosa',
       '4.6,3.6,1.0,0.2,Iris-setosa', '5.1,3.3,1.7,0.5,Iris-setosa',
       '4.8,3.4,1.9,0.2,Iris-setosa', '5.0,3.0,1.6,0.2,Iris-setosa',
       '5.0,3.4,1.6,0.4,Iris-setosa', '5.2,3.5,1.5,0.2,Iris-setosa',
       '5.2,3.4,1.4,0.2,Iris-setos