In [1]:
import numpy as np

In [98]:
arr = np.arange(10)
arr,type(arr)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), numpy.ndarray)

In [99]:
num_list = list(arr)

In [100]:
num_list = [1,2,3]
np.array(num_list)

array([1, 2, 3])

### 计算速度比较

In [30]:
%time for _ in range(100):arr*2

CPU times: user 142 µs, sys: 0 ns, total: 142 µs
Wall time: 146 µs


In [31]:
%time for _ in range(100):[x*2 for x in list(num_list) ]

CPU times: user 4.96 ms, sys: 650 µs, total: 5.61 ms
Wall time: 5.09 ms


### numpy 基础

In [63]:
data = np.random.randn(2,4)
data

array([[-0.74440532, -0.67804882, -0.70928332,  1.40068768],
       [-0.64225956, -0.03816082,  1.61846424, -0.07782131]])

In [37]:
[1,2,3] + [4]

[1, 2, 3, 4]

In [39]:
np.array([1,2,3]) + np.array([4,5,6])

array([5, 7, 9])

In [42]:
data.shape

(2, 4)

In [44]:
data.dtype

dtype('float64')

In [48]:
data.ndim

2

In [49]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [52]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [54]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [57]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [84]:
data

array([[-0.74440532, -0.67804882, -0.70928332,  1.40068768],
       [-0.64225956, -0.03816082,  1.61846424, -0.07782131]])

In [76]:
np.array([312123122],dtype=np.int)

array([312123122])

In [85]:
data.astype(np.string_)

array([[b'-0.7444053202344614', b'-0.6780488228389017',
        b'-0.7092833230472848', b'1.4006876789132743'],
       [b'-0.6422595567904229', b'-0.038160817676143134',
        b'1.6184642388399544', b'-0.07782130789403816']], dtype='|S32')

In [109]:
# slice
arr[1:5] = 100
arr

array([  0, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [108]:
data
data[0][0], data[1,2]

(-0.7444053202344614, 1.6184642388399544)

### 运算

In [91]:
data

array([[-0.74440532, -0.67804882, -0.70928332,  1.40068768],
       [-0.64225956, -0.03816082,  1.61846424, -0.07782131]])

In [89]:
data * 10

array([[-7.4440532 , -6.78048823, -7.09283323, 14.00687679],
       [-6.42259557, -0.38160818, 16.18464239, -0.77821308]])

In [90]:
data + data

array([[-1.48881064, -1.35609765, -1.41856665,  2.80137536],
       [-1.28451911, -0.07632164,  3.23692848, -0.15564262]])

In [116]:
data > 0

array([[False, False, False,  True],
       [False, False,  True, False]])

In [122]:
~(data > 0)

array([[ True,  True,  True, False],
       [ True,  True, False,  True]])

In [120]:
data2 = np.arange(8).reshape(2,4)
data2

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [123]:
data2[data > 0] = 0

In [124]:
data2

array([[0, 1, 2, 0],
       [4, 5, 0, 7]])

In [125]:
num_list = [12,25,-1,12] 
for num in num_list:
    if num <0:
        print(num)

-1


In [129]:
np.array(num_list)[(np.array(num_list) < 0)]

array([-1])

In [130]:
data

array([[-0.74440532, -0.67804882, -0.70928332,  1.40068768],
       [-0.64225956, -0.03816082,  1.61846424, -0.07782131]])

In [134]:
data[data>0]

array([1., 1.])

In [144]:
# 转置
data.T

array([[-0.74440532, -0.64225956],
       [-0.67804882, -0.03816082],
       [-0.70928332,  1.        ],
       [ 1.        , -0.07782131]])

In [169]:
# 点积
arr1 = np.arange(1,3).reshape(2,1)

In [171]:
arr1

array([[1],
       [2]])

In [175]:
arr2 = np.arange(1,3).reshape(1,2)
arr2

array([[1, 2]])

In [173]:
np.dot(arr1,arr2)

array([[1, 2],
       [2, 4]])

In [179]:
arr3 = np.arange(1,5).reshape(2,2)
arr3

array([[1, 2],
       [3, 4]])

In [186]:
arr3

array([[1, 2],
       [3, 4]])

In [181]:
np.dot(arr3,arr3)

array([[ 7, 10],
       [15, 22]])

In [190]:
arr3.transpose((1,0))

array([[1, 3],
       [2, 4]])

In [192]:
arr4 = np.arange(16).reshape(2,2,4)
arr4

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [194]:
arr4.ndim

3

In [202]:
arr4.transpose((2,1,0))

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

In [216]:
steps = np.random.randint(0,2,size=1000)*2-1

In [219]:
steps

array([-1, -1, -1,  1, -1,  1,  1, -1, -1, -1, -1, -1,  1, -1,  1, -1, -1,
       -1, -1, -1, -1, -1, -1,  1, -1,  1, -1, -1,  1, -1, -1,  1, -1,  1,
       -1, -1, -1, -1,  1, -1, -1,  1,  1,  1, -1, -1,  1, -1, -1,  1,  1,
        1,  1,  1, -1,  1,  1,  1, -1,  1,  1,  1,  1, -1,  1,  1,  1,  1,
       -1,  1,  1,  1,  1,  1, -1,  1, -1, -1, -1,  1, -1, -1, -1,  1,  1,
        1,  1,  1,  1,  1, -1, -1,  1,  1, -1,  1, -1,  1,  1,  1, -1,  1,
       -1,  1, -1,  1,  1, -1,  1,  1, -1, -1,  1, -1, -1, -1,  1,  1,  1,
       -1, -1, -1,  1,  1,  1, -1, -1,  1,  1,  1,  1, -1, -1,  1,  1,  1,
       -1, -1, -1, -1,  1,  1,  1,  1, -1, -1, -1,  1,  1,  1,  1,  1,  1,
       -1,  1, -1,  1, -1, -1,  1, -1,  1,  1,  1,  1,  1,  1,  1,  1, -1,
       -1,  1,  1,  1,  1, -1,  1, -1, -1,  1,  1,  1,  1, -1,  1, -1,  1,
       -1,  1,  1, -1,  1,  1,  1, -1, -1, -1,  1, -1,  1,  1,  1, -1,  1,
        1,  1,  1, -1, -1,  1,  1, -1, -1, -1,  1,  1,  1, -1, -1, -1,  1,
       -1, -1,  1, -1, -1

In [217]:
walk = steps.cumsum()

In [220]:
walk.min()

-19