In [2]:
import numpy as np

In [3]:
arr = np.arange(10)
arr,type(arr)

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]), numpy.ndarray)

In [4]:
num_list = list(arr)

In [6]:
num_list = [1,2,3]
np.array(num_list)

array([1, 2, 3])

### 计算速度比较

In [7]:
%time for _ in range(100):arr*2

CPU times: user 168 µs, sys: 7 µs, total: 175 µs
Wall time: 179 µs


In [8]:
%time for _ in range(100):[x*2 for x in list(num_list) ]

CPU times: user 91 µs, sys: 0 ns, total: 91 µs
Wall time: 94.9 µs


### numpy 基础

In [13]:
data = np.random.randn(2,4)
data

array([[-1.04000699,  1.06644397, -0.20486162, -0.61835882],
       [-0.61787891, -0.78111663, -1.38134913, -0.64184984]])

In [14]:
[1,2,3] + [4]

[1, 2, 3, 4]

In [15]:
np.array([1,2,3]) + np.array([4,5,6])

array([5, 7, 9])

In [16]:
data.shape

(2, 4)

In [17]:
data.dtype

dtype('float64')

In [18]:
data.ndim

2

In [19]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [21]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [22]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [23]:
data

array([[-1.04000699,  1.06644397, -0.20486162, -0.61835882],
       [-0.61787891, -0.78111663, -1.38134913, -0.64184984]])

In [24]:
np.array([312123122],dtype=np.int)

array([312123122])

In [27]:
data.astype(np.string_)

array([[b'-1.0400069854021672', b'1.0664439666129553',
        b'-0.20486162279204762', b'-0.618358816821144'],
       [b'-0.6178789065987492', b'-0.7811166274996385',
        b'-1.3813491331488106', b'-0.6418498353841651']], dtype='|S32')

In [29]:
# slice
arr = np.arange(10)
arr[1:5] = 100
arr

array([  0, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [38]:
num_list = [i for i in range(9)]
num_list[1:5] = [100]
num_list

[0, 100, 5, 6, 7, 8]

In [30]:
data
data[0][0], data[1,2]

(-1.0400069854021672, -1.3813491331488106)

### 运算

In [39]:
data

array([[-1.04000699,  1.06644397, -0.20486162, -0.61835882],
       [-0.61787891, -0.78111663, -1.38134913, -0.64184984]])

In [40]:
data * 10

array([[-10.40006985,  10.66443967,  -2.04861623,  -6.18358817],
       [ -6.17878907,  -7.81116627, -13.81349133,  -6.41849835]])

In [41]:
data + data

array([[-2.08001397,  2.13288793, -0.40972325, -1.23671763],
       [-1.23575781, -1.56223325, -2.76269827, -1.28369967]])

In [44]:
data > 0

array([[False,  True, False, False],
       [False, False, False, False]])

In [45]:
~(data > 0)

array([[ True, False,  True,  True],
       [ True,  True,  True,  True]])

In [46]:
data2 = np.arange(8).reshape(2,4)
data2

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [47]:
data2[data > 0] = 0

In [48]:
data2

array([[0, 0, 2, 3],
       [4, 5, 6, 7]])

In [49]:
num_list = [12,25,-1,12] 
for num in num_list:
    if num <0:
        print(num)

-1


In [50]:
np.array(num_list)[(np.array(num_list) < 0)]

array([-1])

In [51]:
data

array([[-1.04000699,  1.06644397, -0.20486162, -0.61835882],
       [-0.61787891, -0.78111663, -1.38134913, -0.64184984]])

In [52]:
data[data>0]

array([1.06644397])

### 矩阵运算

In [53]:
# 转置
data.T

array([[-1.04000699, -0.61787891],
       [ 1.06644397, -0.78111663],
       [-0.20486162, -1.38134913],
       [-0.61835882, -0.64184984]])

In [54]:
# 点积
arr1 = np.arange(1,3).reshape(2,1)

In [60]:
arr1

array([[1],
       [2]])

In [58]:
arr2 = np.arange(1,3).reshape(1,2)
arr2

array([[1, 2]])

In [57]:
np.dot(arr1,arr2)

array([[1, 2],
       [2, 4]])

In [61]:
np.dot(arr2,arr1)

array([[5]])

In [63]:
arr3 = np.arange(1,5).reshape(2,2)
arr3

array([[1, 2],
       [3, 4]])

In [64]:
arr3

array([[1, 2],
       [3, 4]])

In [65]:
np.dot(arr3,arr3)

array([[ 7, 10],
       [15, 22]])

In [66]:
arr3

array([[1, 2],
       [3, 4]])

In [69]:
arr3.T

array([[1, 3],
       [2, 4]])

In [70]:
arr3.transpose((1,0))

array([[1, 3],
       [2, 4]])

In [192]:
arr4 = np.arange(16).reshape(2,2,4)
arr4

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [194]:
arr4.ndim

3

In [202]:
arr4.transpose((2,1,0))

array([[[ 0,  8],
        [ 4, 12]],

       [[ 1,  9],
        [ 5, 13]],

       [[ 2, 10],
        [ 6, 14]],

       [[ 3, 11],
        [ 7, 15]]])

In [72]:
np.arange(16).reshape(4,2,2)

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15]]])

In [81]:
steps = np.random.randint(0,2,size=100)*2-1

In [82]:
steps

array([ 1,  1, -1,  1,  1,  1, -1,  1,  1, -1, -1, -1,  1,  1, -1, -1,  1,
        1,  1,  1,  1,  1, -1,  1,  1,  1, -1,  1,  1,  1, -1, -1, -1,  1,
        1,  1, -1,  1,  1,  1,  1, -1,  1,  1,  1,  1,  1, -1,  1, -1,  1,
       -1,  1,  1,  1, -1,  1, -1,  1, -1, -1,  1,  1,  1,  1, -1, -1,  1,
        1,  1,  1,  1,  1, -1, -1, -1, -1,  1, -1,  1,  1,  1,  1,  1, -1,
        1,  1,  1, -1,  1, -1, -1, -1, -1,  1,  1, -1, -1, -1, -1])

In [83]:
walk = steps.cumsum()

In [84]:
walk.min()

1

In [85]:
timeit("Z.view(np.float16)[...] = 0", globals())

63.1 ns ± 0.71 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
